---
  - hosts: servers
    become: true

    roles:
      # - andrewrothstein.starship -- does not run on raspbian

    tasks:
    - name: install packages
      package:
        name:
          - htop
          - neofetch
          - fish
          - curl
          - docker.io
          - vim
          - restic
          - syncthing
          - docker-compose
          - nfs-kernel-server
          - tmux

    - name: adding existing user chandler to group docker
      user:
        name: chandler
        groups: docker
        append: yes

    - name: Create the starship config directory if it does not exist
      ansible.builtin.file:
        path: /home/chandler/.config/starship
        state: directory
        mode: '0755'
      tags:
        - starship

    - name: copy custom starship file
      copy:
        src: "{{ playbook_dir }}/../files/starship.toml"
        dest: /home/chandler/.config/starship.toml
        owner: chandler
        group: chandler
      tags:
        - starship

    - name: Create the fish config directory if it does not exist
      ansible.builtin.file:
        path: /home/chandler/.config/fish
        state: directory
        mode: '0755'
      tags:
        - fish

    - name: copy fish config
      copy:
        src: "{{ playbook_dir }}/../files/config.fish"
        dest: /home/chandler/.config/fish/config.fish
        owner: chandler
        group: chandler
      tags:
        - fish

    - name: Set login shell of user {{ ansible_ssh_user }} to `/usr/bin/fish` with `usermod`
      ansible.builtin.command: usermod --shell /usr/bin/fish {{ ansible_ssh_user }}
      become: true
      changed_when: false
      tags:
        - fish

    - name: add ansible user
      user:
        name: ansible
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: "{{ playbook_dir }}/../files/ansible_sudoer"
        dest: /etc/sudoers.d/ansiblee
        owner: root
        group: root
        mode: 0440

    - name: add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: ansible
        minute: "0"
        hour: "0"
        job: ansible-pull -o -U https://github.com/chantron/ansible.git

    - name: Enable syncthing service
      ansible.builtin.systemd:
        name: syncthing@chandler.service
        state: started
        enabled: true
